FROM cypress/browsers:node12.13.0-chrome78-ff70-brave78

ENV WORK /build

RUN mkdir -p ${WORK}
WORKDIR ${WORK}

# Install Cypress and dependencies
COPY ./e2e/package.json ./package.json
RUN yarn

ARG APP_ENVIRONMENT
ENV ENVIRONMENT=${APP_ENVIRONMENT}
ARG APP_CYPRESS_KEY
ENV CYPRESS_KEY=${APP_CYPRESS_KEY}

# Generate .env file from args
ARG HSLID_CYPRESS_READ_ACCESS_USERNAME
RUN echo "HSLID_CYPRESS_READ_ACCESS_USERNAME="${HSLID_CYPRESS_READ_ACCESS_USERNAME} >> .env
ARG HSLID_CYPRESS_READ_ACCESS_PASSWORD
RUN echo "HSLID_CYPRESS_READ_ACCESS_PASSWORD="${HSLID_CYPRESS_READ_ACCESS_PASSWORD} >> .env
ARG HSLID_CYPRESS_WRITE_ACCESS_USERNAME
RUN echo "HSLID_CYPRESS_WRITE_ACCESS_USERNAME="${HSLID_CYPRESS_WRITE_ACCESS_USERNAME} >> .env
ARG HSLID_CYPRESS_WRITE_ACCESS_PASSWORD
RUN echo "HSLID_CYPRESS_WRITE_ACCESS_PASSWORD="${HSLID_CYPRESS_WRITE_ACCESS_PASSWORD} >> .env
ARG CLIENT_ID
RUN echo "CLIENT_ID="${CLIENT_ID} >> .env
ARG CLIENT_SECRET
RUN echo "CLIENT_SECRET="${CLIENT_SECRET} >> .env

COPY ./e2e/cypress/ ./cypress
COPY ./e2e/cypress.${ENVIRONMENT}.json .
ADD ./e2e/cypress.${ENVIRONMENT}.json cypress.json

CMD yarn run cypress run -C cypress.json --record --key=${CYPRESS_KEY}